### ISSUE TITLE
Default language is Swedish

### ISSUE THREAD

**Issue by airon90** [tirithen/kodi-remote#5]
Is it because you set the translation file name as "en-US.properties" instead of just "en.properties" while [default_locale](https://github.com/tirithen/kodi-remote/blob/master/manifest.webapp#L5) is "en"?

**Comment by tirithen** [comment]
Thank you for the report, yes that is probably the case, I will try to debug the issue by setting the OS language to a language that does not have a translation.

Fantastic translation contributions by the way, I made a Google Form to try to get translations into more languages http://goo.gl/forms/O0cnwk3GXn from those not using GitHub.

**Comment by airon90** [comment]
Thank you! :)
BTW, many Firefox OS apps are translated on Transifex.
Here is the how-to: https://developer.mozilla.org/en-US/Apps/Build/Localization/App_Localization_with_Transifex ;)

**Comment by tirithen** [comment]
Thank you, I'll check it out! :)

I have this strange problem on my phone, I changed to en-US but when I update the application with the new translations and change the language on my phone, the application is still in Swedish, even after removing the app and restarting the phone. I feel like I am missing something here, will keep trying to get my head around this. 

I find the documentation on this to be a real mess with a lot of different implementations on the mozilla developer site, I have summarized the variations I found here http://stackoverflow.com/questions/28639301/how-to-work-with-localization-translations-in-firefox-os-b2g .

**Comment by tirithen** [comment]
I found a solution, it was an issue with mismatch between l10n.js and localization link tags versions, more details here http://stackoverflow.com/questions/28639301/how-to-work-with-localization-translations-in-firefox-os-b2g . As soon as the new version gets approved by Mozilla this issue will be fixed.

**Comment by airon90** [comment]
Thank you!

**Comment by tirithen** [comment]
The new version is published now.

**Comment by airon90** [comment]
:+1: Thank you!
